CombinatorialGames.lean, CombinatorialGames/Game/Ordinal.lean, CombinatorialGames/Game/PGame.lean, CombinatorialGames/Surreal/Basic.lean, CombinatorialGames/Surreal/Ordinal.lean
Mathlib PR [#21980](https://github.com/leanprover-community/mathlib4/pull/21980).
=> feat: move `Surreal.toOrdinal` to new file

CombinatorialGames/Game/Basic.lean, CombinatorialGames/Game/Domineering.lean, CombinatorialGames/Game/Ordinal.lean, CombinatorialGames/Game/PGame.lean, CombinatorialGames/Game/Short.lean, CombinatorialGames/Surreal/Basic.lean
We address most porting notes, remove obsolete ones, and clean up proofs along the way.
There's three remaining porting notes in the `Short` file, but those will get cleaned up anyways once we refactor the titular definition.
=> chore: address most porting notes

.vscode/settings.json
artificially imposes the 100-character line limit in vscode with a visual ruler.
=> chore: add vscode ruler

CombinatorialGames/Surreal/Basic.lean, CombinatorialGames/Surreal/Ordinal.lean
Mathlib PR [#21979](https://github.com/leanprover-community/mathlib4/pull/21979).
=> feat: basic API for `Surreal.toOrdinal`

CombinatorialGames/Game/Concrete.lean
We define a concrete game as a type endowed with two well-founded relations, determining the ways in which Left and Right can change the game state. We then provide some basic API to turn a concrete game state into a `PGame`.
This is intended to supersede the existing `State` API, which only works for finite games.
=> feat: concrete games

CombinatorialGames/Counterexamples/Multiplication.lean, CombinatorialGames/Game/Basic.lean, CombinatorialGames/Game/Birthday.lean, CombinatorialGames/Game/Impartial.lean, CombinatorialGames/Game/Nim.lean, CombinatorialGames/Game/Ordinal.lean, CombinatorialGames/Game/PGame.lean, CombinatorialGames/Game/Short.lean, CombinatorialGames/Game/Special.lean, CombinatorialGames/Game/State.lean, CombinatorialGames/Nimber/Basic.lean, CombinatorialGames/Nimber/Field.lean, CombinatorialGames/Surreal/Basic.lean, CombinatorialGames/Surreal/Dyadic.lean, CombinatorialGames/Surreal/Multiplication.lean, CombinatorialGames/Surreal/Ordinal.lean
This would be seen as complete bikeshedding over at Mathlib... but since the codebase is so much smaller now I think we can afford some stylistic regularity.
Did a few other minor golfs where I was able to find them.
=> chore: replace `fun _ => _` by `fun _ ↦ _`

CombinatorialGames/Game/Concrete.lean, CombinatorialGames/Game/Specific/Poset.lean
Named this incorrectly; the new name matches `Ordinal.toLeftMovesToPGame`.
=> chore: `toLeftMovesPGame` → `toLeftMovesToPGame`

CombinatorialGames.lean, CombinatorialGames/Game/IGame.lean, CombinatorialGames/IGame/IGame.lean
We define up to the `AddCommMonoid` instance on `IGame`. #29
There's some results I haven't ported yet like `x - x ≈ 0` or `x ≤ y → z + x ≤ z + y`. I think a lot of the results that existed on `PGame` could be simplified by first building the quotient `Game = Antisymmetrization IGame`, proving the `OrderedAddCommGroup` instance on it, and then "porting back" the results via def-eq. So I'd like to do that before proving the more advanced relations between orders and arithemetic on `IGame`.
For now I've put everything in an `IGame` folder - of course, when the refactor is over, the idea is to put everything back in its place, overwriting whatever we had before.
=> feat: `IGame` part 1

CombinatorialGames/IGame/IGame.lean
We prove that addition and subtraction on `IGame` respect equivalence. This means the `PGame` file has now been completely ported (save for the stuff on inserting/removing options), and we can start work on redefining `Game` in terms of `IGame`.
=> feat: missing order results on `IGame`

CombinatorialGames/IGame/IGame.lean
We minimize the `PGame` file to the bare minimum needed to set up `IGame`, and embed it as the first section of the file.
=> feat: embed `PGame` construction in `IGame` file

CombinatorialGames.lean, CombinatorialGames/IGame/Basic.lean
wasn't caught in CI because `CombinatorialGames` didn't index every file in `IGame`.
=> fix(IGame/Basic): index in CombinatorialGames & fix namespace

CombinatorialGames/IGame/IGame.lean
Simp isn't very good when there's multiple nested binders involved, and these expressions give a nicer form to work with.
=> feat: convenience lemmas for `∀ z ∈ (x + y).leftMoves`, etc.

CombinatorialGames/IGame/IGame.lean, CombinatorialGames/IGame/Ordinal.lean, CombinatorialGames/IGame/Special.lean
We implement a simple tactic capable of proving simple inequalities on games. The idea is to use this for computation, instead of trying to square the circle through barely functional decidability tactics.
=> feat: `game_cmp` tactic

CombinatorialGames/IGame/Special.lean
Like tiny and miny, we define more games that slowly introduce background that center around temperature theory: switches have a confusion interval [x, -x] (not present in this PR), where a confusion interval of G is the set of games that are incomparable with G.
=> feat: switches

CombinatorialGames/Counterexamples/Multiplication.lean, CombinatorialGames/IGame/Special.lean
I think I was a bit too hasty in accepting the PR. You can prove `star_mul_star` as an equality rather than just an equivalence. Also, if we're already using notation for `star`, might as well do so for `star'` too.
=> fix: tweak counterexample file

CombinatorialGames.lean, CombinatorialGames/Game/Basic.lean, CombinatorialGames/Game/IGame.lean, CombinatorialGames/Mathlib/Order.lean, CombinatorialGames/Surreal/Basic.lean, CombinatorialGames/Surreal/Division.lean, CombinatorialGames/Surreal/Multiplication.lean
This is Mathlib PR [14498](https://github.com/leanprover-community/mathlib4/pull/14498). Though I based the definition of the game inverse on Mathlib, the proof was basically remade from scratch, simplifying it from 600 lines down to 200. In particular, we can avoid having to "normalize" `x` by simply being a bit more careful with the inductive hypotheses.
Closes #12.
=> feat: surreal division!

CombinatorialGames/Game/Basic.lean, CombinatorialGames/Surreal/Basic.lean
I'm a bit unsure as to what API we should have for `Surreal.ofSets`, but I think that should become clearer once we start making use of it (this is needed e.g. to define `ω ^ x`).
=> feat: surreal number from left and right sets

CombinatorialGames/Game/Basic.lean, CombinatorialGames/Game/IGame.lean, CombinatorialGames/Surreal/Basic.lean, CombinatorialGames/Surreal/Division.lean
We define `IntCast` and `RatCast` instances for `IGame` in the obvious way, and prove that they interact as expected with the instances from `Game` and `Surreal`.
=> feat: define `IntCast` and `RatCast` for games

CombinatorialGames/Game/Basic.lean, CombinatorialGames/Game/IGame.lean, CombinatorialGames/Game/Ordinal.lean, CombinatorialGames/Surreal/Basic.lean, CombinatorialGames/Surreal/Ordinal.lean
Most notably, we introduce notation `{s | t}ˢ` for `Surreal.ofSets s t (by aesop)`, which makes it slightly less painful to work with.
We also fix some small `PGame` → `IGame` typos.
=> feat: extra theorems on `ofSets`

CombinatorialGames/Game/Ordinal.lean, CombinatorialGames/Surreal/Ordinal.lean
Since #88 adds `Real.toIGame` and the like, we have to rename a few theorems to make room.
=> feat: rename `mk_toIGame` lemmas

CombinatorialGames/Game/Basic.lean, CombinatorialGames/Surreal/Division.lean, CombinatorialGames/Surreal/Multiplication.lean, CombinatorialGames/Surreal/Real.lean
We lose out on some small convenience from having the order embedding structure available immediately, but in exchange we get consistency with the casts from other numeric types.
Also, move some theorems I forgot to move in #88.
=> feat: make `Real.toIGame` a cast

CombinatorialGames.lean, CombinatorialGames/Surreal/Numeric.lean
We define the canonical map from the dyadic numbers into `IGame` and prove some basic properties.
This PR really is more about the dyadic rational numbers than about game theory. Since Mathlib doesn't have the dyadic rationals, we have to set up a lot of stuff on our own. Note the conscious decision not to use `Localization.Away 2` - at this point, using it would be much more trouble than it'd be worth.
=> feat: define `Dyadic.toIGame`

CombinatorialGames/Game/Short.lean, CombinatorialGames/Surreal/Numeric.lean, CombinatorialGames/Surreal/Sign.lean
Mostly just a housekeeping PR:
- Added `Dyadic.mkRat` since it seems nicer than explicitly calling the constructor. 
- Added `Dyadic.num` and `Dyadic.den` as abbreviations. 
- Made a convenience `dyadic_wf` macro.
- Proved that `Dyadic.toIGame x` is `Short` (forgot that in the previous PR).
=> feat: more progress on `Dyadic.toIGame`

CombinatorialGames/Game/IGame.lean
Fail over to the default elaborator if the relation is not defeq to LE.
This *should* be the last PR fixing the delab.
=> fix: delab antisymmrel and incomprel (again)

.github/workflows/pages.yml
Otherwise, the build job cancels the deploy one.
=> ci: mv concurrency to workflow level

CombinatorialGames/Game/IGame.lean
We can prove `mul_zero` without induction, and we only need to use `aesop` once to prove `mul_one`, rather than twice.
=> feat(Game/IGame): small speedup

CombinatorialGames/Game/Small.lean, CombinatorialGames/Surreal/Basic.lean, CombinatorialGames/Surreal/Division.lean
To match the new Mathlib convention.
=> fix: `le_of_not_lt` → `le_of_not_gt`

CombinatorialGames/Surreal/Pow.lean, CombinatorialGames/Surreal/Real.lean
For some reason, `Real.toIGame` and `IGame.wpow` were locked to return `IGame.{0}`. Also updated a docstring.
=> fix: make `Real.toIGame` universe polymorphic

CombinatorialGames/Game/Basic.lean, CombinatorialGames/Game/Computability/FGame.lean, CombinatorialGames/Game/IGame.lean, CombinatorialGames/Game/Loopy/Basic.lean, CombinatorialGames/Game/Special.lean, CombinatorialGames/Nimber/Basic.lean, CombinatorialGames/Surreal/Basic.lean, CombinatorialGames/Surreal/Pow.lean
As a small drive-by fix, pre-games → games in docstrings (`PGame` does not exist anymore!)
=> feat: use `recommended_spelling`

CombinatorialGames/Nimber/Simplicity.lean
We introduce `Nimber.IsNthDegreeClosed`, which states that a nimber contains all roots of polynomials of degree ≤ n. We then prove various convenience results about this and `Nimber.IsAlgClosed`.
=> feat: n-th degree closed fields

CombinatorialGames/Nimber/SimplestExtension/Algebraic.lean
This name matches [`IsAlgClosed.exists_root`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/FieldTheory/IsAlgClosed/Basic.html#IsAlgClosed.exists_root) (as I should have noticed much earlier!)
=> chore: `IsNthDegreeClosed.has_root` → `IsNthDegreeClosed.exists_root`

CombinatorialGames/Nimber/SimplestExtension/Basic.lean, CombinatorialGames/Nimber/SimplestExtension/Polynomial.lean
We introduce `IsField.embed`, which reinterprets a polynomial as existing in the subfield for an element `IsField x`.
We could have introduced this as `IsRing.embed` instead, but that has the trouble that Lean can't infer a field instance for `h.toSubring` even when `h : IsField x`, and some later results will require a field.
=> feat: `IsField.embed`

CombinatorialGames/Game/Loopy/Basic.lean
Also protect `MulTy.moves`. This avoids the name clash with `LGame.moves`.
=> chore: rename `moves` variables to `mov`

CombinatorialGames/Game/Concrete.lean, CombinatorialGames/Game/Impartial/Basic.lean, CombinatorialGames/Game/Impartial/Grundy.lean
We make it so that the `Impartial.mk` constructor takes in an `∀ p, ∀ y ∈ x.moves p, Impartial y` argument, instead of separate arguments for left and right games. This removes some redundancy in our proofs.
=> chore: symmetrize `Impartial` API further

CombinatorialGames/Counterexamples/Multiplication.lean, CombinatorialGames/Game/Basic.lean, CombinatorialGames/Game/Concrete.lean, CombinatorialGames/Game/Functor.lean, CombinatorialGames/Game/IGame.lean, CombinatorialGames/Game/Loopy/Basic.lean, CombinatorialGames/Game/Loopy/IGame.lean, CombinatorialGames/Game/Order.lean, CombinatorialGames/Game/Special.lean, CombinatorialGames/Surreal/Basic.lean
A recent Mathlib PR made [`Shrink`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Logic/Small/Defs.html#Shrink) computable, which through a domino effect now means that a lot of our basic definitions on games are computable too.
This doesn't really do much for us. But at least we don't have to write `noncomputable section` literally everywhere!
=> feat: make definitions computable

CombinatorialGames/Game/Computability/FGame.lean, CombinatorialGames/Game/Special.lean, CombinatorialGames/Surreal/Multiplication.lean
This PR mostly just removes references to `PGame`, which no longer exists.
=> doc: update docstrings

CombinatorialGames/Nimber/SimplestExtension/Basic.lean
The previous version was just the special case `x = y`.
=> feat: more general version of `IsField.mul_eq_of_lt`

CombinatorialGames/Counterexamples/Multiplication.lean, CombinatorialGames/Game/Basic.lean, CombinatorialGames/Game/Concrete.lean, CombinatorialGames/Game/Functor.lean, CombinatorialGames/Game/IGame.lean, CombinatorialGames/Game/Loopy/Basic.lean, CombinatorialGames/Game/Loopy/IGame.lean, CombinatorialGames/Game/Order.lean, CombinatorialGames/Game/Special.lean, CombinatorialGames/Surreal/Basic.lean
`Shrink` was re-made noncomputable only a few days after due to a soundness issue.
Reverts vihdzp/combinatorial-games#232
=> Revert "feat: make definitions computable"

CombinatorialGames.lean, CombinatorialGames/Game/Impartial/Grundy.lean, CombinatorialGames/Game/Impartial/Multiplication.lean
In an upcoming refactor I want to redefine nim addition `a + b` directly as `grundy (nim a + nim b)`. This would leave the public API exactly the same, but massively simplify various proofs (e.g. commutativity and associativity of `Nimber` would follow from commutativity and associativity of `Game`). 
This does mean I have to move a few things around, since `Game.Impartial.Grundy` would become an import of `Nimber.Basic`, rather than the other way around. In particular, this stuff about multiplication has to be pulled out. (It could go in the `Nimber.Field` file, but the material feels different enough to warrant a new file).
=> chore: new file `Game.Impartial.Multiplication`
