vihdzp/combinatorial-games

CombinatorialGames/Counterexamples/Multiplication.lean
CombinatorialGames/Game/Basic.lean
CombinatorialGames/Game/Birthday.lean
CombinatorialGames/Game/Domineering.lean
CombinatorialGames/Game/Impartial.lean
CombinatorialGames/Game/Nim.lean
CombinatorialGames/Game/Ordinal.lean
CombinatorialGames/Game/PGame.lean
CombinatorialGames/Game/Short.lean
CombinatorialGames/Game/State.lean
CombinatorialGames/Surreal/Basic.lean
CombinatorialGames/Surreal/Dyadic.lean
CombinatorialGames/Surreal/Multiplication.lean

This isn't really necessary anymore now that all of this has its own repo.

chore: remove `SetTheory` namespace

---

CombinatorialGames/Game/Impartial.lean

Mathlib PR [#21073](https://github.com/leanprover-community/mathlib4/pull/21073).

feat: strategy stealing

---

CombinatorialGames.lean
CombinatorialGames/Counterexamples/Multiplication.lean
CombinatorialGames/Game/Basic.lean
CombinatorialGames/Game/Birthday.lean
CombinatorialGames/Game/Impartial.lean
CombinatorialGames/Game/Nim.lean
CombinatorialGames/Game/Ordinal.lean
CombinatorialGames/Game/PGame.lean
CombinatorialGames/Mathlib/AntisymmRel.lean
CombinatorialGames/Surreal/Basic.lean
CombinatorialGames/Surreal/Dyadic.lean
CombinatorialGames/Surreal/Multiplication.lean

Mathlib PR [#21086](https://github.com/leanprover-community/mathlib4/pull/21086).

feat: `PGame.Equiv` → `AntisymmRel`

---

CombinatorialGames/Game/Impartial.lean
CombinatorialGames/Game/Nim.lean
CombinatorialGames/Game/Ordinal.lean
CombinatorialGames/Game/PGame.lean

Since this is a new repository, it doesn't make sense to maintain old deprecations.

chore: remove deprecations

---

CombinatorialGames/Game/Impartial.lean
CombinatorialGames/Game/Nim.lean

Mathlib PR [#21110](https://github.com/leanprover-community/mathlib4/pull/21110).

feat: improve iff lemmas on impartial games

---

CombinatorialGames/Game/Basic.lean
CombinatorialGames/Game/Birthday.lean
CombinatorialGames/Game/Impartial.lean
CombinatorialGames/Game/Nim.lean
CombinatorialGames/Game/Ordinal.lean
CombinatorialGames/Game/PGame.lean
CombinatorialGames/Game/Relabelling.lean
CombinatorialGames/Game/Short.lean
CombinatorialGames/Surreal/Basic.lean
CombinatorialGames/Surreal/Ordinal.lean

https://github.com/leanprover-community/mathlib4/pull/7162
Co-Authored-By: Yuyang Zhao 赵雨扬 <zhao.yu-yang@foxmail.com>

refactor: separate out relabelling

---

CombinatorialGames/IGame/IGame.lean

We write a proper module docstring for `IGame`, based largely on the pre-existing one on `PGame`.

feat: add module docstring on `IGame` file

---

CombinatorialGames/IGame/Basic.lean
CombinatorialGames/IGame/IGame.lean

Game multiplication is up next, which I'm not excited about.

feat: `Game` as quotient of `IGame`

---

CombinatorialGames.lean
CombinatorialGames/IGame/IGame.lean
CombinatorialGames/Mathlib/CompRel.lean

We define the `fuzzy` relation and add some very basic theorems.
This provisionally embeds Mathlib PR [#19580](https://github.com/leanprover-community/mathlib4/pull/19580)

feat: fuzzy relation

---

CombinatorialGames/IGame/IGame.lean

typos in IGame I didn't catch before.

chore(IGame): fix typos

---

.vscode/settings.json
CombinatorialGames/IGame/Special.lean

Port #24 to our new `IGame` framework. Advances #23.

feat: tiny and miny (`IGame`)

---

CombinatorialGames/IGame/Basic.lean
CombinatorialGames/IGame/IGame.lean

There's some high level goal sorcery going on in these proofs, but at least we can all agree they're much nicer than their `PGame` counterparts.
The heartbeats increase in `mk_mul_assoc` is unfortunate, but completely expected, given that we're applying the inductive hypothesis 56 times in total!

feat: `IGame` multiplication

---

CombinatorialGames.lean
CombinatorialGames/IGame/Concrete.lean

Port the code on `ConcreteGame` to `IGame`.

feat: concrete `IGame`

---

CombinatorialGames.lean
CombinatorialGames/IGame/Basic.lean
CombinatorialGames/IGame/IGame.lean
CombinatorialGames/IGame/Ordinal.lean
CombinatorialGames/IGame/Special.lean

I modified the API a bit, making `Ordinal.toIGame` an `OrderEmbedding`, in exchange for having to prove a few extra auxiliary theorems.

feat: `Ordinal.toIGame`

---

CombinatorialGames.lean
CombinatorialGames/IGame/Basic.lean
CombinatorialGames/IGame/IGame.lean
CombinatorialGames/Surreal/Basic.lean

This file is mostly a direct port. Note that `Numeric` is now an instance (to match `Impartial`).

feat: `Surreal` based on `IGame`

---

CombinatorialGames/IGame/Special.lean

We define `½ = {0 | 1}` and prove `½ + ½ ≈ 1`.

feat: `IGame.half`

---

CombinatorialGames/Counterexamples/Multiplication.lean

thanks to `game_cmp`, the proofs here have been substantially shortened!

feat: port mult counterexample

---

README.md

As pointed out on [Zulip](https://leanprover.zulipchat.com/#narrow/channel/113488-general/topic/Combinatorial.20game.20theory.20repository/near/504973135), tic-tac-toe and chess aren't actually combinatorial games in the sense this repository is interested in, as they can end in ties.
(Are there better-known games we can use as examples? Chomp and Hackenbush seem to mostly only be played within mathematical circles)

feat: better examples of combinatorial games

---

CombinatorialGames/Game/Small.lean

This file is more of a blueprint.
This defines small games and dicotic games, opening a small `proof_wanted` how dicotic games are not part of the surreals, and beginning the proof that they are equivalent to small games.
Notes:
- Cast between ℝ to Game (only for the infinitesimal definition - I am aware that this is not easy by any means.)

feat: begin small

---

CombinatorialGames/Game/Short.lean

feat: more theorems on `Short`

---

CombinatorialGames/Game/IGame.lean

feat: add `IsOption` to aesop simp

---

CombinatorialGames/Surreal/Numeric.lean

feat: nsmul, zsmul, and pow for `Dyadic` + `CanLift` instance to `ℤ`

---

CombinatorialGames/Game/IGame.lean

Fixes a problem where the equiv and fuzzyrel delaborators would not give hover information. Also cleans up a TODO.

fix: fix equiv and fuzzyrel delab

---

CombinatorialGames/Surreal/Numeric.lean

This mimics what we did with `Real.toIGame`.

feat: make `Dyadic.toIGame` a coercion

---

CombinatorialGames/Game/Birthday.lean

chore: modify small birthday instances

---

CombinatorialGames/Game/Basic.lean
CombinatorialGames/Surreal/Basic.lean

This re-does #121 with somewhat shorter proofs, by going through `Game.ofSets` first.

feat: some `ofSets` lemmas (again)

---

CombinatorialGames/Game/Specific/Nim.lean

attached review PR since some of the golfs depend on the slightly changed def. This can be closed and added manually, or merged into #139.

chore: golf

---

CombinatorialGames/Nimber/Basic.lean
CombinatorialGames/Nimber/Field.lean

- It's the simplest extension theorem, not the simplicity theorem
- Nimber multiplication also arises from the Sprague-Grundy theorem
- mimicks → mimics

doc: improve `Nimber` docstrings

---

CombinatorialGames/Game/Computability/FGame.lean
CombinatorialGames/Game/IGame.lean
CombinatorialGames/Mathlib/Order.lean
CombinatorialGames/Surreal/Division.lean
scripts/noshake.json

We set up a `noshake.json` file so that `lake exe shake` can work, and fix the few redundant imports that we had.

feat: set up `shake` command

---

CombinatorialGames/Game/Canonical.lean
CombinatorialGames/Game/IGame.lean
CombinatorialGames/Mathlib/Neg.lean
CombinatorialGames/Surreal/Cut.lean
CombinatorialGames/Surreal/Multiplication.lean

Surprised I didn't think of adding these earlier, the results speak for themselves.

chore: new simp lemmas `forall_mem_neg` and `exists_mem_neg`

---

CombinatorialGames/Game/IGame.lean
CombinatorialGames/Game/Loopy/Basic.lean

chore: use `ext1` tactic

---

CombinatorialGames/Surreal/Real.lean

I use these in a branch of mine.

feat: more simp lemmas for `Real.toSurreal`

---

CombinatorialGames/Game/Short.lean

This is essentially the same reasoning as #224.

chore: symmetrize `Short` API further

---

CombinatorialGames/Surreal/Basic.lean
CombinatorialGames/Surreal/Division.lean
CombinatorialGames/Surreal/Multiplication.lean
CombinatorialGames/Surreal/Pow.lean
CombinatorialGames/Surreal/Real.lean

chore: symmetrize `Numeric` API further

---

CombinatorialGames/Game/Player.lean
CombinatorialGames/Game/Small.lean

chore: symmetrize `Dicotic` API further

---

CombinatorialGames/Game/Loopy/Basic.lean
CombinatorialGames/Game/Loopy/IGame.lean
CombinatorialGames/Game/Loopy/Outcome.lean

Should `Stopper` and `StopperFor` be typeclasses? I'm leaning towards no, since they're much less compositional than other typeclasses like `Numeric` or `Impartial`, but I'd like to hear opinions on this.

feat: stoppers
